// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CorrectSwiftPMFormat",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "CorrectSwiftPMFormat",
            targets: ["AppModule"],
            bundleIdentifier: "com.original.CorrectSwiftPMFormat",
            teamIdentifier: "347C6X6X6T",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/kelvinjou/NotationViewDependentPackage", .branch("main")),
        .package(url: "https://github.com/KelvinMihir/NotationView", .branch("main"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "PlotView", package: "notationview"),
                .product(name: "RhythmView", package: "notationview"),
                .product(name: "ScoreView", package: "notationview"),
                .product(name: "StaffView", package: "notationview")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)