// swift-tools-version: 5.5

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CorrectSwiftPMFormat",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "CorrectSwiftPMFormat",
            targets: ["AppModule"],
            bundleIdentifier: "com.original.CorrectSwiftPMFormat",
            teamIdentifier: "347C6X6X6T",
            displayVersion: "1.0",
            bundleVersion: "1",
            iconAssetName: "AppIcon",
            accentColorAssetName: "AccentColor",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/musical77/MusicScore", .branch("main")),
        .package(url: "https://github.com/kelvinjou/NotationViewDependentPackage", .branch("main")),
        .package(url: "https://github.com/dn-m/Graphics", .branch("latest"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Articulations", package: "notationviewdependentpackage"),
                .product(name: "Duration", package: "notationviewdependentpackage"),
                .product(name: "Dynamics", package: "notationviewdependentpackage"),
                .product(name: "MusicModel", package: "notationviewdependentpackage"),
                .product(name: "Pitch", package: "notationviewdependentpackage"),
                .product(name: "MusicScore", package: "musicscore"),
                .product(name: "Geometry", package: "graphics"),
                .product(name: "GraphicsTesting", package: "graphics"),
                .product(name: "Path", package: "graphics"),
                .product(name: "QuartzAdapter", package: "graphics"),
                .product(name: "Rendering", package: "graphics"),
                .product(name: "SVG", package: "graphics")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
